[codestyle]
workspace_dir='~/my_project/atcoder/problems/'
lang='python'

[etc]
download_without_login=true

[codestyle]
indent_type='space' # 'tab' or 'space'
indent_width=4
template_file='~/my_project/atcoder/utils/template.py'
workspace_dir='~/my_project/atcoder/problems/'
lang='python'
# code_generator_file="~/custom_code_generator.py"
[postprocess]
exec_on_each_problem_dir='clang-format -i ./*.cpp'
exec_on_contest_dir='touch CMakeLists.txt'

[etc]
download_without_login=false
parallel_download=false
save_no_session_cache=false
skip_existing_problems=false
in_example_format="in_{}.txt"
out_example_format="out_{}.txt"
